# Generated by Django 2.2.28 on 2023-03-10 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0002_auto_20230310_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 14, 47, 26, 851815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='category_images/default.png', upload_to='category_images'),
        ),
    ]
