# Generated by Django 2.2.28 on 2023-03-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0004_auto_20230310_1655'),
        ('gearStore', '0004_auto_20230310_1640'),
    ]

    operations = [
    ]
