# Generated by Django 2.2.28 on 2023-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0005_merge_20230310_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dateAdded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='dateAdded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
