# Generated by Django 2.2.28 on 2023-03-15 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gearStore', '0006_auto_20230310_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE')], default='SMALL', max_length=30),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBorrowed', models.DateField(auto_now_add=True)),
                ('dateToReturn', models.DateField()),
                ('gearItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearStore.Gear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
