# Generated by Django 2.2.28 on 2023-03-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0007_auto_20230315_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearStore.UserProfile'),
        ),
    ]
