# Generated by Django 2.2.28 on 2023-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0009_auto_20230315_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='password123', max_length=64)),
            ],
        ),
    ]
