# Generated by Django 2.2.28 on 2023-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearStore', '0010_adminpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='picture',
            field=models.ImageField(default='gear_images/default.png', upload_to='gear_images'),
        ),
    ]
